### ISSUE TITLE
Error when running python alexa-tv.py

### ISSUE THREAD

**Issue by ghost** [akhan23wgu/amazon-alexa-lg-tv#2]
Hi, 

I am having an issue when trying to run the python script.

Any help would be great
```
Traceback (most recent call last):
  File "alexa-tv.py", line 67, in <module>
    p = fauxmo.poller()
  File "/Users/xxxx/Downloads/amazon-alexa-lg-tv-master/fauxmo.py", line 67, in __init__
    self.poller = select.poll()
AttributeError: 'module' object has no attribute 'poll'
```

**Comment by akhan23wgu** [comment]
You need to install the requests module, and whatever else is missing after
that.

Do "pip install requests".


On Oct 5, 2017 2:07 PM, "dayzer1" <notifications@github.com> wrote:

Hi,

I am having an issue when trying to run the python script.

Any help would be great

python alexa-tv.py
Traceback (most recent call last):
  File "alexa-tv.py", line 15, in <module>
    import fauxmo
  File "/Users/aronday/Downloads/amazon-alexa-lg-tv-master/fauxmo.py",
line 31, in <module>
    import requests
ImportError: No module named requests

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akhan23wgu/amazon-alexa-lg-tv/issues/2>, or mute the
thread

**Comment by akhan23wgu** [comment]
Closing - he switched to Ubuntu and all is well :+1: 

Unfortunately there is no way to search inside Netflix. It might be possible with the Magic Remote, I know it supports search on YouTube, so Netflix might be possible.

http://www.youtube.com/watch?v=uoxYO9DslkA&t=1m1s

**Comment by akhan23wgu** [comment]
Closing - he switched to Ubuntu and all is well :+1: 

Unfortunately there is no way to search inside Netflix. It might be possible with the Magic Remote, I know it supports search on YouTube, so Netflix might be possible.

http://www.youtube.com/watch?v=uoxYO9DslkA&t=1m1s
